replicaCount: 2 # Default value for dev

image:
  repository: my-dockerhub-repo/task-demo
  pullPolicy: Always
  tag: "latest"  # Default image tag

service:
  name: task-demo
  type: ClusterIP
  port: 8080

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 75

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: task-demo.local
      paths:
        - /
  tls: []

resources:
  requests:
    memory: "256Mi"
    cpu: "500m"
  limits:
    memory: "512Mi"
    cpu: "1"
