apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-task-demo
  labels:
    app: {{ .Release.Name }}-task-demo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-task-demo
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-task-demo
    spec:
      containers:
          - name: task-demo
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            ports:
              - containerPort: {{ .Values.service.port }}
            resources:
              requests:
                memory: {{ .Values.resources.requests.memory }}
                cpu: {{ .Values.resources.requests.cpu }}
              limits:
                memory: {{ .Values.resources.limits.memory }}
                cpu: {{ .Values.resources.limits.cpu }}
