apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-task-demo
  labels:
    app: {{ .Release.Name }}-task-demo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-task-demo
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-task-demo
    spec:
      containers:
      - name: "task-demo"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: {{ .Values.service.port }}

        volumeMounts:
        - name: data-volume
          mountPath: {{ .Values.app.container.mountPath }}

        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.path }}
            port: {{ .Values.service.port }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}

        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.path }}
            port: {{ .Values.service.port }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: {{ .Values.persistentVolumeClaim.name }}
