apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-task-demo
spec:
  selector:
    app: {{ .Release.Name }}-task-demo
  ports:
      - protocol: TCP
        port: {{ .Values.service.port }}
        targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
