name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Production branch
      - develop # Development branch
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker Image
        run: |
          docker build -t sawnjordan/java-task-demo:${{ github.sha }} .
          docker tag sawnjordan/java-task-demo:${{ github.sha }} sawnjordan/java-task-demo:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

#      - name: Set up Kubernetes CLI (kubectl)
#        uses: azure/setup-kubectl@v1
#        with:
#          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Set up Docker CLI
        uses: docker/setup-buildx-action@v2

      - name: Authenticate to DockerHub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

#      - name: Create Kubernetes Docker registry secret
#        run: |
#          kubectl create secret docker-registry my-dockerhub-secret \
#            --docker-server=https://index.docker.io/v1/ \
#            --docker-username=${{ secrets.DOCKER_USERNAME }} \
#            --docker-password=${{ secrets.DOCKER_TOKEN }} \
#            --dry-run=client -o yaml | kubectl apply -f -

      - name: Push Docker image to Docker Hub
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            docker push sawnjordan/java-task-demo:${{ github.sha }}
          else
            docker push sawnjordan/java-task-demo:dev
          fi

#      - name: Set up Helm
#        uses: azure/setup-helm@v1
#
#      - name: Deploy to Kubernetes using Helm
#        run: |
#          # Set namespace and values file based on the branch (main for prod, develop for dev)
#          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
#            helm upgrade --install task-demo ./helm \
#              --namespace prod \
#              --set image.tag=${{ github.sha }} \
#              --set image.pullSecret=my-dockerhub-secret \
#              -f ./helm/values-prod.yaml
#          else
#            helm upgrade --install task-demo ./helm \
#              --namespace dev \
#              --set image.tag=dev \
#              --set image.pullSecret=my-dockerhub-secret \
#              -f ./helm/values-dev.yaml
#          fi
